/*
** 
**  electrifier
** 
**  Copyright 2018 Thorsten Jung, www.electrifier.org
**  
**  Licensed under the Apache License, Version 2.0 (the "License");
**  you may not use this file except in compliance with the License.
**  You may obtain a copy of the License at
**  
**      http://www.apache.org/licenses/LICENSE-2.0
**  
**  Unless required by applicable law or agreed to in writing, software
**  distributed under the License is distributed on an "AS IS" BASIS,
**  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**  See the License for the specific language governing permissions and
**  limitations under the License.
**
*/


using System;


namespace common.Interop
{
    public class WinNT
    {
        /// <summary>
        /// File Attribute Constants
        /// 
        /// (Generated by P/Invoke Interop Assistant)
        /// <seaalso href="https://docs.microsoft.com/en-us/windows/desktop/FileIO/file-attribute-constants"/>
        /// </summary>
        [Flags]
        public enum File_Attribute : uint
        {
            Archive = 32,                       /// FILE_ATTRIBUTE_ARCHIVE -> 0x00000020
            Compressed = 2048,                  /// FILE_ATTRIBUTE_COMPRESSED -> 0x00000800
            Device = 64,                        /// FILE_ATTRIBUTE_DEVICE -> 0x00000040
            Directory = 16,                     /// FILE_ATTRIBUTE_DIRECTORY -> 0x00000010
            Encrypted = 16384,                  /// FILE_ATTRIBUTE_ENCRYPTED -> 0x00004000
            Hidden = 2,                         /// FILE_ATTRIBUTE_HIDDEN -> 0x00000002
            Normal = 128,                       /// FILE_ATTRIBUTE_NORMAL -> 0x00000080
            Not_Content_Indexed = 8192,         /// FILE_ATTRIBUTE_NOT_CONTENT_INDEXED -> 0x00002000
            Offline = 4096,                     /// FILE_ATTRIBUTE_OFFLINE -> 0x00001000
            Readonly = 1,                       /// FILE_ATTRIBUTE_READONLY -> 0x00000001
            Reparse_Point = 1024,               /// FILE_ATTRIBUTE_REPARSE_POINT -> 0x00000400
            Sparse_File = 512,                  /// FILE_ATTRIBUTE_SPARSE_FILE -> 0x00000200
            System = 4,                         /// FILE_ATTRIBUTE_SYSTEM -> 0x00000004
            Temporary = 256,                    /// FILE_ATTRIBUTE_TEMPORARY -> 0x00000100
        };
    }
}
