//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electrifier.Core.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindowForm_RibbonMarkup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowForm_RibbonMarkup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("electrifier.Core.Forms.MainWindowForm.RibbonMarkup", typeof(MainWindowForm_RibbonMarkup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string cmdBtnClipboardCopy_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnClipboardCopy_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string cmdBtnClipboardCut_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnClipboardCut_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string cmdBtnClipboardPaste_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnClipboardPaste_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string cmdBtnOrganizeDelete_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnOrganizeDelete_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        internal static string cmdBtnOrganizeMoveTo_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnOrganizeMoveTo_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string cmdBtnOrganizeRename_LabelTitle {
            get {
                return ResourceManager.GetString("cmdBtnOrganizeRename_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string cmdGrpHomeClipboard_LabelTitle {
            get {
                return ResourceManager.GetString("cmdGrpHomeClipboard_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize.
        /// </summary>
        internal static string cmdGrpHomeOrganize_LabelTitle {
            get {
                return ResourceManager.GetString("cmdGrpHomeOrganize_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Panel.
        /// </summary>
        internal static string cmdHomeNewShellBrowserPanel_LabelTitle {
            get {
                return ResourceManager.GetString("cmdHomeNewShellBrowserPanel_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new electrifier panel..
        /// </summary>
        internal static string cmdHomeNewShellBrowserPanel_TooltipDescription {
            get {
                return ResourceManager.GetString("cmdHomeNewShellBrowserPanel_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new electrifier panel.
        /// </summary>
        internal static string cmdHomeNewShellBrowserPanel_TooltipTitle {
            get {
                return ResourceManager.GetString("cmdHomeNewShellBrowserPanel_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string cmdTabHome_LabelTitle {
            get {
                return ResourceManager.GetString("cmdTabHome_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string cmdTabShare_LabelTitle {
            get {
                return ResourceManager.GetString("cmdTabShare_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string cmdTabView_LabelTitle {
            get {
                return ResourceManager.GetString("cmdTabView_LabelTitle", resourceCulture);
            }
        }
    }
}
