//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;
using RibbonLib.Interop;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint QuickAccessToolbar = 59900;
            public const uint BtnQATOpenNewShellBrowserPanel = 59902;
            public const uint BtnQATHelp = 59999;
            public const uint BtnAppApplicationMenu = 100;
            public const uint BtnAppOpenNewWindow = 101;
            public const uint BtnAppOpenNewShellBrowserPanel = 102;
            public const uint BtnAppOpenCommandPrompt = 103;
            public const uint BtnAppOpenWindowsPowerShell = 104;
            public const uint BtnAppChangeElectrifierOptions = 110;
            public const uint BtnAppChangeFolderAndSearchOptions = 111;
            public const uint SplAppHelpMenu = 120;
            public const uint BtnAppHelp = 121;
            public const uint BtnAppHelp_AboutElectrifier = 122;
            public const uint BtnAppHelp_AboutWindows = 125;
            public const uint BtnAppClose = 130;
            public const uint TabHome = 1000;
            public const uint GrpHomeClipboard = 1100;
            public const uint BtnClipboardCut = 1110;
            public const uint SplClipboardCopy = 2;
            public const uint BtnClipboardCopy = 1120;
            public const uint BtnClipboardCopyFullFilePaths = 1121;
            public const uint BtnClipboardCopyFileNames = 1122;
            public const uint BtnClipboardCopyDirectoryPaths = 1123;
            public const uint SplClipboardPaste = 3;
            public const uint BtnClipboardPaste = 1130;
            public const uint BtnClipboardPasteAsNewFile = 1131;
            public const uint BtnClipboardPasteAsNewText = 11111;
            public const uint BtnClipboardPasteAsNewTextFile = 1132;
            public const uint BtnClipboardPasteAsNewImage = 11112;
            public const uint BtnClipboardPasteAsNewBMPFile = 1133;
            public const uint BtnClipboardPasteAsNewJPGFile = 1134;
            public const uint BtnClipboardPasteAsNewPNGFile = 1135;
            public const uint BtnClipboardPasteAsNewGIFFile = 1136;
            public const uint BtnClipboardHistory = 1140;
            public const uint GrpHomeOrganise = 1200;
            public const uint BtnOrganiseMoveTo = 1201;
            public const uint BtnOrganiseCopyTo = 1202;
            public const uint BtnOrganiseDelete = 1203;
            public const uint BtnOrganiseRename = 1204;
            public const uint GrpHomeSelect = 1500;
            public const uint BtnSelectConditional = 1501;
            public const uint BtnSelectSelectAll = 1502;
            public const uint BtnSelectSelectNone = 1503;
            public const uint BtnSelectInvertSelection = 1504;
            public const uint GrpHomeView = 1600;
            public const uint DdbHomeViewLayout = 1610;
            public const uint BtnHomeViewExtraLargeIcons = 1611;
            public const uint BtnHomeViewLargeIcons = 1612;
            public const uint BtnHomeViewMediumIcons = 1613;
            public const uint BtnHomeViewSmallIcons = 1614;
            public const uint BtnHomeViewList = 1615;
            public const uint BtnHomeViewDetails = 1616;
            public const uint BtnHomeViewTiles = 1617;
            public const uint BtnHomeViewContent = 1618;
            public const uint TabGrpDesktopTools = 41111;
            public const uint TabDesktopIconManagement = 40100;
            public const uint GrpDesktopIconSettings = 40101;
            public const uint BtnDesktopIconSettingsSaveLayout = 40102;
            public const uint BtnDesktopIconSettingsRestoreLayout = 40103;
            public const uint BtnDesktopIconSettingsLaunchControlPanel = 40104;
            public const uint CbxDesktopIconSettingsSpacingVertical = 40105;
            public const uint CbxDesktopIconSettingsSpacingHorizontal = 40106;
            public const uint GrpDesktopShortcuts = 40110;
            public const uint BtnDesktopShortcutsDefaults = 40111;
            public const uint BtnDesktopShortcutsValidate = 40112;
        }

        // ContextPopup CommandName

        private static bool initialized;

        public Ribbon Ribbon { get; private set; }
        public RibbonQuickAccessToolbar QuickAccessToolbar { get; private set; }
        public RibbonButton BtnQATOpenNewShellBrowserPanel { get; private set; }
        public RibbonHelpButton BtnQATHelp { get; private set; }
        public RibbonApplicationMenu BtnAppApplicationMenu { get; private set; }
        public RibbonButton BtnAppOpenNewWindow { get; private set; }
        public RibbonButton BtnAppOpenNewShellBrowserPanel { get; private set; }
        public RibbonButton BtnAppOpenCommandPrompt { get; private set; }
        public RibbonButton BtnAppOpenWindowsPowerShell { get; private set; }
        public RibbonButton BtnAppChangeElectrifierOptions { get; private set; }
        public RibbonButton BtnAppChangeFolderAndSearchOptions { get; private set; }
        public RibbonSplitButton SplAppHelpMenu { get; private set; }
        public RibbonButton BtnAppHelp { get; private set; }
        public RibbonButton BtnAppHelp_AboutElectrifier { get; private set; }
        public RibbonButton BtnAppHelp_AboutWindows { get; private set; }
        public RibbonButton BtnAppClose { get; private set; }
        public RibbonTab TabHome { get; private set; }
        public RibbonGroup GrpHomeClipboard { get; private set; }
        public RibbonButton BtnClipboardCut { get; private set; }
        public RibbonSplitButton SplClipboardCopy { get; private set; }
        public RibbonButton BtnClipboardCopy { get; private set; }
        public RibbonButton BtnClipboardCopyFullFilePaths { get; private set; }
        public RibbonButton BtnClipboardCopyFileNames { get; private set; }
        public RibbonButton BtnClipboardCopyDirectoryPaths { get; private set; }
        public RibbonSplitButton SplClipboardPaste { get; private set; }
        public RibbonButton BtnClipboardPaste { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewFile { get; private set; }
        public RibbonMenuGroup BtnClipboardPasteAsNewText { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewTextFile { get; private set; }
        public RibbonMenuGroup BtnClipboardPasteAsNewImage { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewBMPFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewJPGFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewPNGFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewGIFFile { get; private set; }
        public RibbonToggleButton BtnClipboardHistory { get; private set; }
        public RibbonGroup GrpHomeOrganise { get; private set; }
        public RibbonButton BtnOrganiseMoveTo { get; private set; }
        public RibbonButton BtnOrganiseCopyTo { get; private set; }
        public RibbonButton BtnOrganiseDelete { get; private set; }
        public RibbonButton BtnOrganiseRename { get; private set; }
        public RibbonGroup GrpHomeSelect { get; private set; }
        public RibbonButton BtnSelectConditional { get; private set; }
        public RibbonButton BtnSelectSelectAll { get; private set; }
        public RibbonButton BtnSelectSelectNone { get; private set; }
        public RibbonButton BtnSelectInvertSelection { get; private set; }
        public RibbonGroup GrpHomeView { get; private set; }
        public RibbonDropDownButton DdbHomeViewLayout { get; private set; }
        public RibbonToggleButton BtnHomeViewExtraLargeIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewLargeIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewMediumIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewSmallIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewList { get; private set; }
        public RibbonToggleButton BtnHomeViewDetails { get; private set; }
        public RibbonToggleButton BtnHomeViewTiles { get; private set; }
        public RibbonToggleButton BtnHomeViewContent { get; private set; }
        public RibbonTabGroup TabGrpDesktopTools { get; private set; }
        public RibbonTab TabDesktopIconManagement { get; private set; }
        public RibbonGroup GrpDesktopIconSettings { get; private set; }
        public RibbonButton BtnDesktopIconSettingsSaveLayout { get; private set; }
        public RibbonButton BtnDesktopIconSettingsRestoreLayout { get; private set; }
        public RibbonButton BtnDesktopIconSettingsLaunchControlPanel { get; private set; }
        public RibbonComboBox CbxDesktopIconSettingsSpacingVertical { get; private set; }
        public RibbonComboBox CbxDesktopIconSettingsSpacingHorizontal { get; private set; }
        public RibbonGroup GrpDesktopShortcuts { get; private set; }
        public RibbonButton BtnDesktopShortcutsDefaults { get; private set; }
        public RibbonButton BtnDesktopShortcutsValidate { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            if (initialized)
                return;
            this.Ribbon = ribbon;
            QuickAccessToolbar = new RibbonQuickAccessToolbar(ribbon, Cmd.QuickAccessToolbar);
            BtnQATOpenNewShellBrowserPanel = new RibbonButton(ribbon, Cmd.BtnQATOpenNewShellBrowserPanel);
            BtnQATHelp = new RibbonHelpButton(ribbon, Cmd.BtnQATHelp);
            BtnAppApplicationMenu = new RibbonApplicationMenu(ribbon, Cmd.BtnAppApplicationMenu);
            BtnAppOpenNewWindow = new RibbonButton(ribbon, Cmd.BtnAppOpenNewWindow);
            BtnAppOpenNewShellBrowserPanel = new RibbonButton(ribbon, Cmd.BtnAppOpenNewShellBrowserPanel);
            BtnAppOpenCommandPrompt = new RibbonButton(ribbon, Cmd.BtnAppOpenCommandPrompt);
            BtnAppOpenWindowsPowerShell = new RibbonButton(ribbon, Cmd.BtnAppOpenWindowsPowerShell);
            BtnAppChangeElectrifierOptions = new RibbonButton(ribbon, Cmd.BtnAppChangeElectrifierOptions);
            BtnAppChangeFolderAndSearchOptions = new RibbonButton(ribbon, Cmd.BtnAppChangeFolderAndSearchOptions);
            SplAppHelpMenu = new RibbonSplitButton(ribbon, Cmd.SplAppHelpMenu);
            BtnAppHelp = new RibbonButton(ribbon, Cmd.BtnAppHelp);
            BtnAppHelp_AboutElectrifier = new RibbonButton(ribbon, Cmd.BtnAppHelp_AboutElectrifier);
            BtnAppHelp_AboutWindows = new RibbonButton(ribbon, Cmd.BtnAppHelp_AboutWindows);
            BtnAppClose = new RibbonButton(ribbon, Cmd.BtnAppClose);
            TabHome = new RibbonTab(ribbon, Cmd.TabHome);
            GrpHomeClipboard = new RibbonGroup(ribbon, Cmd.GrpHomeClipboard);
            BtnClipboardCut = new RibbonButton(ribbon, Cmd.BtnClipboardCut);
            SplClipboardCopy = new RibbonSplitButton(ribbon, Cmd.SplClipboardCopy);
            BtnClipboardCopy = new RibbonButton(ribbon, Cmd.BtnClipboardCopy);
            BtnClipboardCopyFullFilePaths = new RibbonButton(ribbon, Cmd.BtnClipboardCopyFullFilePaths);
            BtnClipboardCopyFileNames = new RibbonButton(ribbon, Cmd.BtnClipboardCopyFileNames);
            BtnClipboardCopyDirectoryPaths = new RibbonButton(ribbon, Cmd.BtnClipboardCopyDirectoryPaths);
            SplClipboardPaste = new RibbonSplitButton(ribbon, Cmd.SplClipboardPaste);
            BtnClipboardPaste = new RibbonButton(ribbon, Cmd.BtnClipboardPaste);
            BtnClipboardPasteAsNewFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewFile);
            BtnClipboardPasteAsNewText = new RibbonMenuGroup(ribbon, Cmd.BtnClipboardPasteAsNewText);
            BtnClipboardPasteAsNewTextFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewTextFile);
            BtnClipboardPasteAsNewImage = new RibbonMenuGroup(ribbon, Cmd.BtnClipboardPasteAsNewImage);
            BtnClipboardPasteAsNewBMPFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewBMPFile);
            BtnClipboardPasteAsNewJPGFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewJPGFile);
            BtnClipboardPasteAsNewPNGFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewPNGFile);
            BtnClipboardPasteAsNewGIFFile = new RibbonButton(ribbon, Cmd.BtnClipboardPasteAsNewGIFFile);
            BtnClipboardHistory = new RibbonToggleButton(ribbon, Cmd.BtnClipboardHistory);
            GrpHomeOrganise = new RibbonGroup(ribbon, Cmd.GrpHomeOrganise);
            BtnOrganiseMoveTo = new RibbonButton(ribbon, Cmd.BtnOrganiseMoveTo);
            BtnOrganiseCopyTo = new RibbonButton(ribbon, Cmd.BtnOrganiseCopyTo);
            BtnOrganiseDelete = new RibbonButton(ribbon, Cmd.BtnOrganiseDelete);
            BtnOrganiseRename = new RibbonButton(ribbon, Cmd.BtnOrganiseRename);
            GrpHomeSelect = new RibbonGroup(ribbon, Cmd.GrpHomeSelect);
            BtnSelectConditional = new RibbonButton(ribbon, Cmd.BtnSelectConditional);
            BtnSelectSelectAll = new RibbonButton(ribbon, Cmd.BtnSelectSelectAll);
            BtnSelectSelectNone = new RibbonButton(ribbon, Cmd.BtnSelectSelectNone);
            BtnSelectInvertSelection = new RibbonButton(ribbon, Cmd.BtnSelectInvertSelection);
            GrpHomeView = new RibbonGroup(ribbon, Cmd.GrpHomeView);
            DdbHomeViewLayout = new RibbonDropDownButton(ribbon, Cmd.DdbHomeViewLayout);
            BtnHomeViewExtraLargeIcons = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewExtraLargeIcons);
            BtnHomeViewLargeIcons = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewLargeIcons);
            BtnHomeViewMediumIcons = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewMediumIcons);
            BtnHomeViewSmallIcons = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewSmallIcons);
            BtnHomeViewList = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewList);
            BtnHomeViewDetails = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewDetails);
            BtnHomeViewTiles = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewTiles);
            BtnHomeViewContent = new RibbonToggleButton(ribbon, Cmd.BtnHomeViewContent);
            TabGrpDesktopTools = new RibbonTabGroup(ribbon, Cmd.TabGrpDesktopTools);
            TabDesktopIconManagement = new RibbonTab(ribbon, Cmd.TabDesktopIconManagement);
            GrpDesktopIconSettings = new RibbonGroup(ribbon, Cmd.GrpDesktopIconSettings);
            BtnDesktopIconSettingsSaveLayout = new RibbonButton(ribbon, Cmd.BtnDesktopIconSettingsSaveLayout);
            BtnDesktopIconSettingsRestoreLayout = new RibbonButton(ribbon, Cmd.BtnDesktopIconSettingsRestoreLayout);
            BtnDesktopIconSettingsLaunchControlPanel = new RibbonButton(ribbon, Cmd.BtnDesktopIconSettingsLaunchControlPanel);
            CbxDesktopIconSettingsSpacingVertical = new RibbonComboBox(ribbon, Cmd.CbxDesktopIconSettingsSpacingVertical);
            CbxDesktopIconSettingsSpacingHorizontal = new RibbonComboBox(ribbon, Cmd.CbxDesktopIconSettingsSpacingHorizontal);
            GrpDesktopShortcuts = new RibbonGroup(ribbon, Cmd.GrpDesktopShortcuts);
            BtnDesktopShortcutsDefaults = new RibbonButton(ribbon, Cmd.BtnDesktopShortcutsDefaults);
            BtnDesktopShortcutsValidate = new RibbonButton(ribbon, Cmd.BtnDesktopShortcutsValidate);
            initialized = true;
        }

    }
}
