//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;
using RibbonLib.Interop;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint CmdQAT = 59901;
            public const uint CmdBtnQAT_OpenNewShellBrowserPanel = 59903;
            public const uint CmdBtnHelp = 59900;
            public const uint CmdBtnApp_ApplicationMenu = 100;
            public const uint CmdBtnApp_OpenNewWindow = 101;
            public const uint CmdBtnApp_OpenNewShellBrowserPanel = 102;
            public const uint CmdBtnApp_OpenCommandPrompt = 103;
            public const uint CmdBtnApp_OpenWindowsPowerShell = 104;
            public const uint CmdBtnApp_ChangeElectrifierOptions = 110;
            public const uint CmdBtnApp_ChangeFolderAndSearchOptions = 111;
            public const uint SplBtnApp_HelpMenu = 120;
            public const uint CmdBtnApp_Help = 121;
            public const uint CmdBtnApp_Help_AboutElectrifier = 122;
            public const uint CmdBtnApp_Help_AboutWindows = 125;
            public const uint CmdBtnApp_Close = 130;
            public const uint CmdTabHome = 1000;
            public const uint CmdGrpHomeClipboard = 1100;
            public const uint CmdBtnClipboardCut = 1110;
            public const uint SplBtnClipboardCopy = 2;
            public const uint CmdBtnClipboardCopy = 1120;
            public const uint CmdClipboardCopyFullFilePaths = 1121;
            public const uint CmdClipboardCopyFileNames = 1122;
            public const uint CmdClipboardCopyDirectoryPaths = 1123;
            public const uint SplBtnClipboardPaste = 3;
            public const uint CmdBtnClipboardPaste = 1130;
            public const uint CmdBtnClipboardPasteAsNewFile = 1131;
            public const uint CmdBtnClipboardPasteAsNewText = 11111;
            public const uint CmdBtnClipboardPasteAsNewTextFile = 1132;
            public const uint CmdBtnClipboardPasteAsNewImage = 11112;
            public const uint CmdBtnClipboardPasteAsNewBMPFile = 1133;
            public const uint CmdBtnClipboardPasteAsNewJPGFile = 1134;
            public const uint CmdBtnClipboardPasteAsNewPNGFile = 1135;
            public const uint CmdBtnClipboardPasteAsNewGIFFile = 1136;
            public const uint CmdBtnClipboardHistory = 1140;
            public const uint CmdGrpHomeOrganise = 1200;
            public const uint CmdBtnOrganiseMoveTo = 1201;
            public const uint CmdBtnOrganiseCopyTo = 1202;
            public const uint CmdBtnOrganiseDelete = 1203;
            public const uint CmdBtnOrganiseRename = 1204;
            public const uint CmdGrpHomeSelect = 1500;
            public const uint CmdBtnSelectConditional = 1501;
            public const uint CmdBtnSelectSelectAll = 1502;
            public const uint CmdBtnSelectSelectNone = 1503;
            public const uint CmdBtnSelectInvertSelection = 1504;
            public const uint CmdGrpHomeView = 1600;
            public const uint CmdDdbHomeViewLayout = 1610;
            public const uint CmdBtnHomeViewExtraLargeIcons = 1611;
            public const uint CmdBtnHomeViewLargeIcons = 1612;
            public const uint CmdBtnHomeViewMediumIcons = 1613;
            public const uint CmdBtnHomeViewSmallIcons = 1614;
            public const uint CmdBtnHomeViewList = 1615;
            public const uint CmdBtnHomeViewDetails = 1616;
            public const uint CmdBtnHomeViewTiles = 1617;
            public const uint CmdBtnHomeViewContent = 1618;
            public const uint CmdDesktopToolsTabGroup = 41111;
            public const uint CmdDesktopIconManagementTab = 40100;
            public const uint CmdDesktopIconSettingsGroup = 40101;
            public const uint CmdDesktopIconSettingsSaveLayoutButton = 40102;
            public const uint CmdDesktopIconSettingsRestoreLayoutButton = 40103;
            public const uint CmdDesktopIconSettingsLaunchControlPanel = 40104;
            public const uint CbxDesktopIconSettingsSpacingVertical = 40105;
            public const uint CbxDesktopIconSettingsSpacingHorizontal = 40106;
            public const uint CmdDesktopShortcutGroup = 40110;
            public const uint CmdDesktopShortcutCreateDefaults = 40111;
            public const uint CmdDesktopShortcutValidate = 40112;
        }

        // ContextPopup CommandName

        private static bool initialized;

        public Ribbon Ribbon { get; private set; }
        public RibbonQuickAccessToolbar QAT { get; private set; }
        public RibbonButton BtnQAT_OpenNewShellBrowserPanel { get; private set; }
        public RibbonHelpButton BtnHelp { get; private set; }
        public RibbonApplicationMenu BtnApp_ApplicationMenu { get; private set; }
        public RibbonButton BtnApp_OpenNewWindow { get; private set; }
        public RibbonButton BtnApp_OpenNewShellBrowserPanel { get; private set; }
        public RibbonButton BtnApp_OpenCommandPrompt { get; private set; }
        public RibbonButton BtnApp_OpenWindowsPowerShell { get; private set; }
        public RibbonButton BtnApp_ChangeElectrifierOptions { get; private set; }
        public RibbonButton BtnApp_ChangeFolderAndSearchOptions { get; private set; }
        public RibbonSplitButton SplBtnApp_HelpMenu { get; private set; }
        public RibbonButton BtnApp_Help { get; private set; }
        public RibbonButton BtnApp_Help_AboutElectrifier { get; private set; }
        public RibbonButton BtnApp_Help_AboutWindows { get; private set; }
        public RibbonButton BtnApp_Close { get; private set; }
        public RibbonTab TabHome { get; private set; }
        public RibbonGroup GrpHomeClipboard { get; private set; }
        public RibbonButton BtnClipboardCut { get; private set; }
        public RibbonSplitButton SplBtnClipboardCopy { get; private set; }
        public RibbonButton BtnClipboardCopy { get; private set; }
        public RibbonButton ClipboardCopyFullFilePaths { get; private set; }
        public RibbonButton ClipboardCopyFileNames { get; private set; }
        public RibbonButton ClipboardCopyDirectoryPaths { get; private set; }
        public RibbonSplitButton SplBtnClipboardPaste { get; private set; }
        public RibbonButton BtnClipboardPaste { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewFile { get; private set; }
        public RibbonMenuGroup BtnClipboardPasteAsNewText { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewTextFile { get; private set; }
        public RibbonMenuGroup BtnClipboardPasteAsNewImage { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewBMPFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewJPGFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewPNGFile { get; private set; }
        public RibbonButton BtnClipboardPasteAsNewGIFFile { get; private set; }
        public RibbonToggleButton BtnClipboardHistory { get; private set; }
        public RibbonGroup GrpHomeOrganise { get; private set; }
        public RibbonButton BtnOrganiseMoveTo { get; private set; }
        public RibbonButton BtnOrganiseCopyTo { get; private set; }
        public RibbonButton BtnOrganiseDelete { get; private set; }
        public RibbonButton BtnOrganiseRename { get; private set; }
        public RibbonGroup GrpHomeSelect { get; private set; }
        public RibbonButton BtnSelectConditional { get; private set; }
        public RibbonButton BtnSelectSelectAll { get; private set; }
        public RibbonButton BtnSelectSelectNone { get; private set; }
        public RibbonButton BtnSelectInvertSelection { get; private set; }
        public RibbonGroup GrpHomeView { get; private set; }
        public RibbonDropDownButton DdbHomeViewLayout { get; private set; }
        public RibbonToggleButton BtnHomeViewExtraLargeIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewLargeIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewMediumIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewSmallIcons { get; private set; }
        public RibbonToggleButton BtnHomeViewList { get; private set; }
        public RibbonToggleButton BtnHomeViewDetails { get; private set; }
        public RibbonToggleButton BtnHomeViewTiles { get; private set; }
        public RibbonToggleButton BtnHomeViewContent { get; private set; }
        public RibbonTabGroup DesktopToolsTabGroup { get; private set; }
        public RibbonTab DesktopIconManagementTab { get; private set; }
        public RibbonGroup DesktopIconSettingsGroup { get; private set; }
        public RibbonButton DesktopIconSettingsSaveLayoutButton { get; private set; }
        public RibbonButton DesktopIconSettingsRestoreLayoutButton { get; private set; }
        public RibbonButton DesktopIconSettingsLaunchControlPanel { get; private set; }
        public RibbonComboBox CbxDesktopIconSettingsSpacingVertical { get; private set; }
        public RibbonComboBox CbxDesktopIconSettingsSpacingHorizontal { get; private set; }
        public RibbonGroup DesktopShortcutGroup { get; private set; }
        public RibbonButton DesktopShortcutCreateDefaults { get; private set; }
        public RibbonButton DesktopShortcutValidate { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            if (initialized)
                return;
            this.Ribbon = ribbon;
            QAT = new RibbonQuickAccessToolbar(ribbon, Cmd.CmdQAT);
            BtnQAT_OpenNewShellBrowserPanel = new RibbonButton(ribbon, Cmd.CmdBtnQAT_OpenNewShellBrowserPanel);
            BtnHelp = new RibbonHelpButton(ribbon, Cmd.CmdBtnHelp);
            BtnApp_ApplicationMenu = new RibbonApplicationMenu(ribbon, Cmd.CmdBtnApp_ApplicationMenu);
            BtnApp_OpenNewWindow = new RibbonButton(ribbon, Cmd.CmdBtnApp_OpenNewWindow);
            BtnApp_OpenNewShellBrowserPanel = new RibbonButton(ribbon, Cmd.CmdBtnApp_OpenNewShellBrowserPanel);
            BtnApp_OpenCommandPrompt = new RibbonButton(ribbon, Cmd.CmdBtnApp_OpenCommandPrompt);
            BtnApp_OpenWindowsPowerShell = new RibbonButton(ribbon, Cmd.CmdBtnApp_OpenWindowsPowerShell);
            BtnApp_ChangeElectrifierOptions = new RibbonButton(ribbon, Cmd.CmdBtnApp_ChangeElectrifierOptions);
            BtnApp_ChangeFolderAndSearchOptions = new RibbonButton(ribbon, Cmd.CmdBtnApp_ChangeFolderAndSearchOptions);
            SplBtnApp_HelpMenu = new RibbonSplitButton(ribbon, Cmd.SplBtnApp_HelpMenu);
            BtnApp_Help = new RibbonButton(ribbon, Cmd.CmdBtnApp_Help);
            BtnApp_Help_AboutElectrifier = new RibbonButton(ribbon, Cmd.CmdBtnApp_Help_AboutElectrifier);
            BtnApp_Help_AboutWindows = new RibbonButton(ribbon, Cmd.CmdBtnApp_Help_AboutWindows);
            BtnApp_Close = new RibbonButton(ribbon, Cmd.CmdBtnApp_Close);
            TabHome = new RibbonTab(ribbon, Cmd.CmdTabHome);
            GrpHomeClipboard = new RibbonGroup(ribbon, Cmd.CmdGrpHomeClipboard);
            BtnClipboardCut = new RibbonButton(ribbon, Cmd.CmdBtnClipboardCut);
            SplBtnClipboardCopy = new RibbonSplitButton(ribbon, Cmd.SplBtnClipboardCopy);
            BtnClipboardCopy = new RibbonButton(ribbon, Cmd.CmdBtnClipboardCopy);
            ClipboardCopyFullFilePaths = new RibbonButton(ribbon, Cmd.CmdClipboardCopyFullFilePaths);
            ClipboardCopyFileNames = new RibbonButton(ribbon, Cmd.CmdClipboardCopyFileNames);
            ClipboardCopyDirectoryPaths = new RibbonButton(ribbon, Cmd.CmdClipboardCopyDirectoryPaths);
            SplBtnClipboardPaste = new RibbonSplitButton(ribbon, Cmd.SplBtnClipboardPaste);
            BtnClipboardPaste = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPaste);
            BtnClipboardPasteAsNewFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewFile);
            BtnClipboardPasteAsNewText = new RibbonMenuGroup(ribbon, Cmd.CmdBtnClipboardPasteAsNewText);
            BtnClipboardPasteAsNewTextFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewTextFile);
            BtnClipboardPasteAsNewImage = new RibbonMenuGroup(ribbon, Cmd.CmdBtnClipboardPasteAsNewImage);
            BtnClipboardPasteAsNewBMPFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewBMPFile);
            BtnClipboardPasteAsNewJPGFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewJPGFile);
            BtnClipboardPasteAsNewPNGFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewPNGFile);
            BtnClipboardPasteAsNewGIFFile = new RibbonButton(ribbon, Cmd.CmdBtnClipboardPasteAsNewGIFFile);
            BtnClipboardHistory = new RibbonToggleButton(ribbon, Cmd.CmdBtnClipboardHistory);
            GrpHomeOrganise = new RibbonGroup(ribbon, Cmd.CmdGrpHomeOrganise);
            BtnOrganiseMoveTo = new RibbonButton(ribbon, Cmd.CmdBtnOrganiseMoveTo);
            BtnOrganiseCopyTo = new RibbonButton(ribbon, Cmd.CmdBtnOrganiseCopyTo);
            BtnOrganiseDelete = new RibbonButton(ribbon, Cmd.CmdBtnOrganiseDelete);
            BtnOrganiseRename = new RibbonButton(ribbon, Cmd.CmdBtnOrganiseRename);
            GrpHomeSelect = new RibbonGroup(ribbon, Cmd.CmdGrpHomeSelect);
            BtnSelectConditional = new RibbonButton(ribbon, Cmd.CmdBtnSelectConditional);
            BtnSelectSelectAll = new RibbonButton(ribbon, Cmd.CmdBtnSelectSelectAll);
            BtnSelectSelectNone = new RibbonButton(ribbon, Cmd.CmdBtnSelectSelectNone);
            BtnSelectInvertSelection = new RibbonButton(ribbon, Cmd.CmdBtnSelectInvertSelection);
            GrpHomeView = new RibbonGroup(ribbon, Cmd.CmdGrpHomeView);
            DdbHomeViewLayout = new RibbonDropDownButton(ribbon, Cmd.CmdDdbHomeViewLayout);
            BtnHomeViewExtraLargeIcons = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewExtraLargeIcons);
            BtnHomeViewLargeIcons = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewLargeIcons);
            BtnHomeViewMediumIcons = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewMediumIcons);
            BtnHomeViewSmallIcons = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewSmallIcons);
            BtnHomeViewList = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewList);
            BtnHomeViewDetails = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewDetails);
            BtnHomeViewTiles = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewTiles);
            BtnHomeViewContent = new RibbonToggleButton(ribbon, Cmd.CmdBtnHomeViewContent);
            DesktopToolsTabGroup = new RibbonTabGroup(ribbon, Cmd.CmdDesktopToolsTabGroup);
            DesktopIconManagementTab = new RibbonTab(ribbon, Cmd.CmdDesktopIconManagementTab);
            DesktopIconSettingsGroup = new RibbonGroup(ribbon, Cmd.CmdDesktopIconSettingsGroup);
            DesktopIconSettingsSaveLayoutButton = new RibbonButton(ribbon, Cmd.CmdDesktopIconSettingsSaveLayoutButton);
            DesktopIconSettingsRestoreLayoutButton = new RibbonButton(ribbon, Cmd.CmdDesktopIconSettingsRestoreLayoutButton);
            DesktopIconSettingsLaunchControlPanel = new RibbonButton(ribbon, Cmd.CmdDesktopIconSettingsLaunchControlPanel);
            CbxDesktopIconSettingsSpacingVertical = new RibbonComboBox(ribbon, Cmd.CbxDesktopIconSettingsSpacingVertical);
            CbxDesktopIconSettingsSpacingHorizontal = new RibbonComboBox(ribbon, Cmd.CbxDesktopIconSettingsSpacingHorizontal);
            DesktopShortcutGroup = new RibbonGroup(ribbon, Cmd.CmdDesktopShortcutGroup);
            DesktopShortcutCreateDefaults = new RibbonButton(ribbon, Cmd.CmdDesktopShortcutCreateDefaults);
            DesktopShortcutValidate = new RibbonButton(ribbon, Cmd.CmdDesktopShortcutValidate);
            initialized = true;
        }

    }
}
